version: '3.0'
services:
  app:
    build: tomcat/
    ports:
    - 8080:8080
    depends_on:
    - mongodb
    hostname: app

  mongodb:
    build: mongodb/
    ports:
    - 27017:27017
    container_name: fly
    volumes:
    - fly_data:/data/db
    - fly_data:/data/configdb
volumes:
  fly_data:
